key = "mixed_model"
label = "Mixed Model"
needs_targets = true
needs_order = false
allows_weights = true
allows_partition = true

[widget_configs.population]
widget = "select"
label = "Population variable"
placeholder = "Select population variable..."
options = { "-v" = "names" }

# TODO: here and in GLM inputs, we should find a way to
# specify that some variables are grouped together (use `+`?)
[widget_configs.population_inputs]
widget = "select"
label = "Random effect terms"
placeholder = "Select random effect terms..."
multiple = true
options = { "-v" = "names" }
